package com.micro.order.dto;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.micro.order.dto.Restaurant;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class OrderDTOFromFE {

    private Integer userId;
    private Restaurant restaurant;
    private List<FoodItemsDTO> foodItemsList;
    // Order id is not here because id is not provided by frontend, but generated by backend

}
