# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: angularapp
# spec:
#   replicas: 1  # the number of replicas as per requirements
#   selector:
#     matchLabels:
#       app: angularapp
#   template:
#     metadata:
#       labels:
#         app: angularapp
#     spec:
#       containers:
#         - name: angular-app-container
#           image: harpzzz/food-app-fe:0.0.2
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 80

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: angular-service
# spec:
#   selector:
#     app: angularapp
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angularapp
  template:
    metadata:
      labels:
        app: angularapp
    spec:
      containers:
        - name: angular-app-container
          image: harpzzz/food-app-fe:0.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 80  
          env:
            - name: PORT
              value: "80"  
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angularapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  