apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://hz-database-1.cdiawi0qg80m.us-west-1.rds.amazonaws.com/restaurantdb
  foodcatalogdb_url: jdbc:mysql://hz-database-1.cdiawi0qg80m.us-west-1.rds.amazonaws.com:3306/foodItemdb
  userdb_url: jdbc:mysql://hz-database-1.cdiawi0qg80m.us-west-1.rds.amazonaws.com:3306/userdb
  orderdb_url: mongodb+srv://admin:Lucky2025zxy!@cluster0.cuhxd.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  